# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class AutoRoundConfig(metaclass=DummyObject):
    _backends = ["auto_round"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["auto_round"])

    @classmethod
    def from_config(cls, *args, **kwargs):
        requires_backends(cls, ["auto_round"])

    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        requires_backends(cls, ["auto_round"])
