# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class BiRefNetModel(metaclass=DummyObject):
    _backends = ["torch", "torchvision"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch", "torchvision"])

    @classmethod
    def from_config(cls, *args, **kwargs):
        requires_backends(cls, ["torch", "torchvision"])

    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        requires_backends(cls, ["torch", "torchvision"])
