# This file is autogenerated by the command `make fix-copies`, do not edit.
# flake8: noqa
from ..utils import DummyObject, requires_backends


class LmsDiscreteScheduler(metaclass=DummyObject):
    _backends = ["scipy"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["scipy"])


class LDMTextToImagePipeline(metaclass=DummyObject):
    _backends = ["scipy"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["scipy"])


class StableDiffusionPipeline(metaclass=DummyObject):
    _backends = ["scipy"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["scipy"])
