# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class QuarkConfig(metaclass=DummyObject):
    _backends = ["quark"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["quark"])

    @classmethod
    def from_config(cls, *args, **kwargs):
        requires_backends(cls, ["quark"])

    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        requires_backends(cls, ["quark"])
