#!/usr/bin/env python
# Copyright 2025 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""DFlash draft-model training (paper: arXiv:2602.06036).

The draft predicts ``block_size - 1`` masked tokens per anchor, conditioned on
hidden states from a frozen autoregressive target. Multi-anchor sparse-attention
training (§4.2 / Appendix A.1, paper-default ``num_anchors=512``) is implemented
via PyTorch FlexAttention.

Data preparation
----------------
The paper (§5.1) trains on responses **regenerated by the target model** for
better target alignment. Recommended recipe:

  1. Serve the target with vLLM or SGLang::

         vllm serve Qwen/Qwen3-4B --port 8000 --served-model-name target

  2. Re-roll the dataset's assistant turns through that server (e.g.
     ``nemo_automodel.components.speculative.regenerate`` or a short asyncio
     loop against ``/v1/chat/completions``).

  3. Point ``--dataset_name`` at the regenerated parquet/jsonl.

Skipping this step trains the draft on a different distribution than the
target produces at inference, which reduces acceptance length.
"""

import argparse
import math
import os
from dataclasses import asdict, dataclass
from typing import Dict, Optional

import torch
import torch.nn.functional as F
from accelerate import Accelerator
from accelerate.logging import get_logger
from accelerate.utils import ProjectConfiguration, set_seed
from datasets import load_dataset
from torch.nn.attention.flex_attention import create_block_mask
from torch.utils.data import DataLoader
from transformers import AutoModel, AutoModelForCausalLM, AutoTokenizer, DataCollatorForLanguageModeling, get_scheduler


logger = get_logger(__name__)


@dataclass
class TrainConfig:
    draft_model_id: str
    target_model_id: str
    dataset_name: str
    dataset_config_name: Optional[str]
    text_column: str

    output_dir: str
    seed: int
    max_train_steps: int
    checkpointing_steps: int
    logging_steps: int

    per_device_train_batch_size: int
    gradient_accumulation_steps: int
    learning_rate: float
    weight_decay: float
    lr_scheduler: str
    lr_warmup_steps: int
    lr_warmup_ratio: float
    max_grad_norm: float

    max_length: int
    block_size: int
    mask_token: str
    loss_decay_gamma: float

    num_anchors: int
    attention_backend: str
    overlap_anchors: bool


def parse_args() -> TrainConfig:
    parser = argparse.ArgumentParser(description="Fine-tune a DFlash draft model with target-conditioned blocks.")

    parser.add_argument("--draft_model_id", type=str, default="z-lab/Qwen3-4B-DFlash-b16")
    parser.add_argument("--target_model_id", type=str, default="Qwen/Qwen3-4B")
    parser.add_argument("--dataset_name", type=str, default="wikitext")
    parser.add_argument("--dataset_config_name", type=str, default="wikitext-2-raw-v1")
    parser.add_argument("--text_column", type=str, default="text")

    parser.add_argument("--output_dir", type=str, default="dflash-output")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--max_train_steps", type=int, default=1000)
    parser.add_argument("--checkpointing_steps", type=int, default=500)
    parser.add_argument("--logging_steps", type=int, default=50)

    parser.add_argument("--per_device_train_batch_size", type=int, default=2)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
    parser.add_argument("--learning_rate", type=float, default=6e-4)
    parser.add_argument("--weight_decay", type=float, default=0.0)
    parser.add_argument(
        "--lr_scheduler", type=str, default="cosine", choices=["linear", "cosine", "cosine_with_restarts"]
    )
    parser.add_argument(
        "--lr_warmup_steps",
        type=int,
        default=0,
        help="Absolute warmup steps. Ignored when --lr_warmup_ratio > 0 (default).",
    )
    parser.add_argument("--lr_warmup_ratio", type=float, default=0.04)
    parser.add_argument("--max_grad_norm", type=float, default=1.0)

    parser.add_argument("--max_length", type=int, default=3072)
    parser.add_argument(
        "--block_size", type=int, default=0, help="Override draft block size (0 uses the model config)."
    )
    parser.add_argument("--mask_token", type=str, default="<|MASK|>")
    parser.add_argument(
        "--loss_decay_gamma",
        type=float,
        default=0.0,
        help="Per-position loss decay γ for w_k = exp(-(k-1)/γ). 0 selects the paper default for the "
        "draft block size (γ=7 for block 16, γ=5 for block 10, γ=4 for block 8, else block_size/2).",
    )
    parser.add_argument(
        "--num_anchors",
        type=int,
        default=512,
        help="Anchor blocks per sequence (paper default 512, Appendix A.1). "
        "With attention_backend=sdpa, keep N small (<=64) to avoid OOM; "
        "flex_attention is required for the full N=512.",
    )
    parser.add_argument(
        "--attention_backend",
        type=str,
        default="flex_attention",
        choices=["sdpa", "flex_attention"],
        help="Sparse mask backend. flex_attention scales to N=512; sdpa materialises a "
        "dense [B,1,N*bs,S+N*bs] mask and is for small-N debugging.",
    )
    parser.add_argument(
        "--no_overlap_anchors",
        dest="overlap_anchors",
        action="store_false",
        help="Disable independent (overlapping) anchor sampling and use stars-and-bars "
        "non-overlapping anchors instead. Caps N at seq_len // block_size.",
    )
    parser.set_defaults(overlap_anchors=True)

    args = parser.parse_args()
    return TrainConfig(**vars(args))


def tokenize_fn(examples: Dict, tokenizer, text_column: str, max_length: int):
    texts = examples[text_column]
    texts = [t for t in texts if isinstance(t, str) and len(t.strip()) > 0]
    return tokenizer(texts, truncation=True, padding=False, max_length=max_length)


def build_target_layer_ids(num_target_layers: int, num_draft_layers: int):
    if num_draft_layers == 1:
        return [int(num_target_layers // 2)]
    start = 1
    end = int(num_target_layers) - 3
    span = end - start
    return [int(round(start + (i * span) / (num_draft_layers - 1))) for i in range(int(num_draft_layers))]


def extract_context_feature(hidden_states, layer_ids):
    offset = 1
    selected_states = [hidden_states[layer_id + offset] for layer_id in layer_ids]
    return torch.cat(selected_states, dim=-1)


def get_target_input_embeddings(model: torch.nn.Module) -> torch.nn.Module:
    embeddings = model.get_input_embeddings()
    if embeddings is None:
        base = getattr(model, "model", None)
        embeddings = getattr(base, "embed_tokens", None)
    if embeddings is None:
        raise ValueError("Target model must expose input embeddings.")
    return embeddings


def get_target_output_embeddings(model: torch.nn.Module) -> torch.nn.Module:
    embeddings = model.get_output_embeddings()
    if embeddings is None:
        embeddings = getattr(model, "lm_head", None)
    if embeddings is None:
        raise ValueError("Target model must expose output embeddings.")
    return embeddings


def sample_anchor_starts(valid_len: int, block_size: int, num_anchors: int, overlap: bool, device: torch.device):
    """Sample anchor positions for multi-block DFlash training.

    Returns a sorted list of ints in ``[1, valid_len - block_size]``. With
    ``overlap=True`` (paper default), anchors are drawn independently and may
    overlap in the original sequence. With ``overlap=False``, anchors are at
    least ``block_size`` apart (caps N at ``(valid_len - 1) // block_size``).
    """
    max_anchor = valid_len - block_size
    if overlap:
        n = max(1, num_anchors)
        starts = torch.randint(1, max_anchor + 1, (n,), device=device).sort().values
    else:
        max_n = max(1, (valid_len - 1) // block_size)
        n = min(num_anchors, max_n)
        perm = torch.randperm(valid_len - n * block_size, device=device)[:n].sort().values
        starts = perm + torch.arange(n, device=device) * block_size + 1
    return [int(s) for s in starts.tolist()]


def build_dflash_mask(
    starts: list, ctx_len: int, block_size: int, backend: str, device: torch.device, dtype: torch.dtype
):
    """Construct the DFlash sparse-attention mask.

    KV layout = [context (ctx_len) | N draft blocks of size block_size]. Each
    block ``b`` attends to context positions ``< starts[b]`` and its own noise
    positions only. Returns a FlexAttention :class:`BlockMask` when
    ``backend="flex_attention"``, otherwise a dense additive ``[1, 1, N*bs, ctx+N*bs]``
    float mask (0 = attended, -inf = masked).
    """
    n = len(starts)
    Q_LEN = n * block_size
    KV_LEN = ctx_len + n * block_size
    anchors = torch.tensor(starts, dtype=torch.long, device=device)

    if backend == "flex_attention":

        def mask_mod(b, h, q_idx, kv_idx):
            q_block = q_idx // block_size
            safe_q_block = q_block.clamp(max=n - 1)
            anchor = anchors[safe_q_block]
            ctx_visible = (kv_idx < ctx_len) & (kv_idx < anchor)
            kv_block = (kv_idx - ctx_len) // block_size
            noise_visible = (kv_idx >= ctx_len) & (q_block == kv_block)
            return (ctx_visible | noise_visible) & (q_block < n)

        return create_block_mask(mask_mod, B=None, H=None, Q_LEN=Q_LEN, KV_LEN=KV_LEN, device=device)

    # SDPA: dense additive mask.
    q_idx = torch.arange(Q_LEN, device=device).view(1, 1, -1, 1)
    kv_idx = torch.arange(KV_LEN, device=device).view(1, 1, 1, -1)
    q_block = q_idx // block_size
    anchor_exp = anchors.view(1, 1, n, 1).repeat_interleave(block_size, dim=2)
    ctx_visible = (kv_idx < ctx_len) & (kv_idx < anchor_exp)
    kv_block = (kv_idx - ctx_len) // block_size
    noise_visible = (kv_idx >= ctx_len) & (q_block == kv_block)
    bool_mask = ctx_visible | noise_visible
    return torch.where(
        bool_mask,
        torch.zeros((), device=device, dtype=dtype),
        torch.full((), float("-inf"), device=device, dtype=dtype),
    )


def main():
    cfg = parse_args()

    project_config = ProjectConfiguration(project_dir=cfg.output_dir, logging_dir=os.path.join(cfg.output_dir, "logs"))
    accelerator = Accelerator(
        gradient_accumulation_steps=cfg.gradient_accumulation_steps,
        project_config=project_config,
    )

    if accelerator.is_main_process:
        os.makedirs(cfg.output_dir, exist_ok=True)
    accelerator.wait_for_everyone()

    set_seed(cfg.seed)
    logger.info("Training configuration: %s", asdict(cfg))

    tokenizer = AutoTokenizer.from_pretrained(cfg.target_model_id, use_fast=True)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    if tokenizer.mask_token_id is None:
        tokenizer.add_special_tokens({"mask_token": cfg.mask_token})

    draft_model = AutoModel.from_pretrained(cfg.draft_model_id, trust_remote_code=True)
    # Route the draft's per-layer attention through transformers'
    # ALL_ATTENTION_FUNCTIONS[_attn_implementation] dispatcher.
    draft_model.config._attn_implementation = cfg.attention_backend

    target_model = AutoModelForCausalLM.from_pretrained(cfg.target_model_id)
    target_model.eval()
    target_model.requires_grad_(False)

    mask_token_id = tokenizer.mask_token_id
    if mask_token_id is None:
        raise ValueError("Tokenizer must define a mask token for DFlash training.")

    input_embeddings = get_target_input_embeddings(target_model)
    output_embeddings = get_target_output_embeddings(target_model)

    block_size = int(cfg.block_size)
    if block_size <= 0:
        block_size = getattr(draft_model, "block_size", None) or getattr(
            getattr(draft_model, "config", None), "block_size", None
        )
    if block_size is None:
        raise ValueError("Draft model must define `block_size` or pass --block_size.")
    block_size = int(block_size)
    if block_size < 2:
        raise ValueError("`block_size` must be at least 2 for DFlash training.")

    # Eq. 4 in the DFlash paper: w_k = exp(-(k-1)/γ) over predicted positions k=1..block_size-1.
    # Defaults from Appendix A.1.
    if cfg.loss_decay_gamma > 0.0:
        loss_gamma = float(cfg.loss_decay_gamma)
    else:
        loss_gamma = {16: 7.0, 10: 5.0, 8: 4.0}.get(block_size, max(2.0, block_size / 2.0))
    pos_weights = torch.exp(-torch.arange(block_size - 1, dtype=torch.float32) / loss_gamma)

    layer_ids = getattr(draft_model, "target_layer_ids", None)
    if layer_ids is None:
        cfg_draft = getattr(draft_model, "config", None)
        num_target_layers = getattr(cfg_draft, "num_target_layers", None)
        num_hidden_layers = getattr(cfg_draft, "num_hidden_layers", None)
        if num_target_layers is None or num_hidden_layers is None:
            raise ValueError("Draft model must expose `target_layer_ids` or `num_target_layers` in config.")
        layer_ids = build_target_layer_ids(int(num_target_layers), int(num_hidden_layers))

    raw_datasets = load_dataset(cfg.dataset_name, cfg.dataset_config_name)
    if "train" not in raw_datasets:
        raise ValueError(f"Dataset {cfg.dataset_name} has no 'train' split.")

    with accelerator.main_process_first():
        tokenized = raw_datasets["train"].map(
            lambda ex: tokenize_fn(ex, tokenizer, cfg.text_column, cfg.max_length),
            batched=True,
            remove_columns=raw_datasets["train"].column_names,
            desc="Tokenizing",
        )

    collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False, return_tensors="pt")
    train_dataloader = DataLoader(
        tokenized, shuffle=True, collate_fn=collator, batch_size=cfg.per_device_train_batch_size, drop_last=True
    )

    optimizer = torch.optim.AdamW(draft_model.parameters(), lr=cfg.learning_rate, weight_decay=cfg.weight_decay)

    num_update_steps_per_epoch = math.ceil(len(train_dataloader) / cfg.gradient_accumulation_steps)
    num_train_epochs = math.ceil(cfg.max_train_steps / num_update_steps_per_epoch)

    if cfg.lr_warmup_ratio > 0.0:
        num_warmup_steps = int(cfg.lr_warmup_ratio * cfg.max_train_steps)
    else:
        num_warmup_steps = cfg.lr_warmup_steps
    lr_scheduler = get_scheduler(
        name=cfg.lr_scheduler,
        optimizer=optimizer,
        num_warmup_steps=num_warmup_steps,
        num_training_steps=cfg.max_train_steps,
    )

    draft_model, optimizer, train_dataloader, lr_scheduler, target_model = accelerator.prepare(
        draft_model, optimizer, train_dataloader, lr_scheduler, target_model
    )
    input_embeddings = get_target_input_embeddings(target_model)
    output_embeddings = get_target_output_embeddings(target_model)
    pos_weights = pos_weights.to(accelerator.device)

    global_step = 0
    draft_model.train()

    for epoch in range(num_train_epochs):
        for batch in train_dataloader:
            with accelerator.accumulate(draft_model):
                input_ids = batch["input_ids"]
                attention_mask = batch.get("attention_mask", torch.ones_like(input_ids))

                valid_lengths = attention_mask.sum(dim=1)
                min_valid = int(valid_lengths.min().item())
                if min_valid <= block_size:
                    continue

                B = input_ids.shape[0]
                device = input_ids.device

                starts = sample_anchor_starts(min_valid, block_size, cfg.num_anchors, cfg.overlap_anchors, device)
                n = len(starts)
                ctx_len = starts[-1]

                # [B, n*block_size] — anchor token then (block_size - 1) mask tokens, repeated.
                block_output_ids = torch.full((B, n * block_size), int(mask_token_id), device=device, dtype=torch.long)
                # [B, n*(block_size - 1)] — supervised targets for each block.
                block_targets = torch.empty((B, n * (block_size - 1)), device=device, dtype=torch.long)
                # [B, n*(block_size - 1)] — supervised positions (1 = supervised, 0 = pad).
                block_loss_mask = torch.empty((B, n * (block_size - 1)), device=device, dtype=attention_mask.dtype)
                for i, s in enumerate(starts):
                    block_output_ids[:, i * block_size] = input_ids[:, s]
                    block_targets[:, i * (block_size - 1) : (i + 1) * (block_size - 1)] = input_ids[
                        :, s + 1 : s + block_size
                    ]
                    block_loss_mask[:, i * (block_size - 1) : (i + 1) * (block_size - 1)] = attention_mask[
                        :, s + 1 : s + block_size
                    ]

                # Position IDs cover the concatenated [context | N draft blocks] sequence so RoPE
                # rotates K_ctx with original positions and each draft block with its anchor's range.
                ctx_pos = torch.arange(ctx_len, device=device)
                block_pos = torch.cat([torch.arange(s, s + block_size, device=device) for s in starts])
                position_ids = torch.cat([ctx_pos, block_pos]).unsqueeze(0).expand(B, -1)

                with torch.no_grad():
                    target_out = target_model(
                        input_ids=input_ids,
                        attention_mask=attention_mask,
                        output_hidden_states=True,
                        use_cache=False,
                    )
                    target_hidden = extract_context_feature(target_out.hidden_states, layer_ids)
                    target_hidden = target_hidden[:, :ctx_len, :]

                # Multi-block sparse attention: a BlockMask (flex) or dense additive mask (sdpa).
                # For n == 1, the slicing of target_hidden already prevents post-anchor leakage,
                # so the mask is only required for n > 1.
                attn_mask = None
                if n > 1:
                    attn_mask = build_dflash_mask(
                        starts,
                        ctx_len=ctx_len,
                        block_size=block_size,
                        backend=cfg.attention_backend,
                        device=device,
                        dtype=target_hidden.dtype,
                    )

                noise_embedding = input_embeddings(block_output_ids)
                draft_kwargs = {
                    "target_hidden": target_hidden,
                    "noise_embedding": noise_embedding,
                    "position_ids": position_ids,
                    "use_cache": False,
                    "is_causal": False,
                }
                if attn_mask is not None:
                    draft_kwargs["attention_mask"] = attn_mask

                draft_hidden = draft_model(**draft_kwargs)
                if not torch.is_tensor(draft_hidden):
                    draft_hidden = getattr(draft_hidden, "last_hidden_state", draft_hidden[0])

                # Drop anchor positions (column 0 of each block); keep the (block_size - 1)
                # predicted positions per block.
                draft_hidden = draft_hidden.view(B, n, block_size, -1)[:, :, 1:, :]
                draft_hidden = draft_hidden.reshape(B, n * (block_size - 1), -1)
                logits = output_embeddings(draft_hidden)
                vocab_size = logits.shape[-1]
                loss = F.cross_entropy(logits.view(-1, vocab_size), block_targets.reshape(-1), reduction="none")
                loss = loss.view(B, n * (block_size - 1))

                # pos_weights is [block_size - 1]; tile across N blocks. Loss mask zeroes out padded
                # positions; both are then broadcast to [B, n*(block_size-1)].
                weights_per_block = pos_weights.to(loss.dtype)[None, :].expand(n, -1).reshape(-1)
                weights = weights_per_block[None, :].expand_as(loss) * block_loss_mask.to(loss.dtype)
                loss = (loss * weights).sum() / weights.sum().clamp_min(1)

                accelerator.backward(loss)
                if accelerator.sync_gradients and cfg.max_grad_norm > 0:
                    accelerator.clip_grad_norm_(draft_model.parameters(), cfg.max_grad_norm)
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad(set_to_none=True)

            if accelerator.sync_gradients:
                global_step += 1

                if global_step % cfg.logging_steps == 0 and accelerator.is_main_process:
                    logger.info("step=%d loss=%.4f lr=%.6g", global_step, loss.item(), lr_scheduler.get_last_lr()[0])

                if cfg.checkpointing_steps > 0 and global_step % cfg.checkpointing_steps == 0:
                    accelerator.wait_for_everyone()
                    if accelerator.is_main_process:
                        save_dir = os.path.join(cfg.output_dir, f"checkpoint-{global_step}")
                        os.makedirs(save_dir, exist_ok=True)
                        unwrapped = accelerator.unwrap_model(draft_model)
                        unwrapped.save_pretrained(save_dir, save_function=accelerator.save)
                        tokenizer.save_pretrained(save_dir)

                if global_step >= cfg.max_train_steps:
                    break

        if global_step >= cfg.max_train_steps:
            break

    accelerator.wait_for_everyone()
    if accelerator.is_main_process:
        final_dir = os.path.join(cfg.output_dir, "final")
        os.makedirs(final_dir, exist_ok=True)
        unwrapped = accelerator.unwrap_model(draft_model)
        unwrapped.save_pretrained(final_dir, save_function=accelerator.save)
        tokenizer.save_pretrained(final_dir)

    logger.info("Done.")


if __name__ == "__main__":
    main()
