# Copyright 2026 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from ..modular_pipeline import SequentialPipelineBlocks
from ..modular_pipeline_utils import OutputParam
from .before_denoise import (
    AnimaImg2ImgSetTimestepsStep,
    AnimaPrepareLatentsStep,
    AnimaSetTimestepsStep,
    AnimaTextConditioningStep,
    AnimaTextInputStep,
)
from .decoders import AnimaProcessImagesOutputStep, AnimaVaeDecoderStep
from .denoise import AnimaDenoiseStep
from .encoders import AnimaImg2ImgVaeEncoderStep, AnimaTextEncoderStep


# auto_docstring
class AnimaCoreDenoiseStep(SequentialPipelineBlocks):
    """
    Denoise block that takes encoded Anima text inputs and runs the denoising process.

      Components:
          text_conditioner (`AnimaTextConditioner`) transformer (`CosmosTransformer3DModel`) scheduler
          (`FlowMatchEulerDiscreteScheduler`) guider (`ClassifierFreeGuidance`)

      Inputs:
          qwen_prompt_embeds (`Tensor`):
              Qwen prompt embeddings generated by the text encoder step.
          qwen_attention_mask (`Tensor`):
              Qwen prompt attention mask generated by the text encoder step.
          t5_input_ids (`Tensor`):
              T5 prompt token ids generated by the text encoder step.
          t5_attention_mask (`Tensor`):
              T5 prompt attention mask generated by the text encoder step.
          negative_qwen_prompt_embeds (`Tensor`, *optional*):
              Negative Qwen prompt embeddings generated by the text encoder step.
          negative_qwen_attention_mask (`Tensor`, *optional*):
              Negative Qwen prompt attention mask generated by the text encoder step.
          negative_t5_input_ids (`Tensor`, *optional*):
              Negative T5 prompt token ids generated by the text encoder step.
          negative_t5_attention_mask (`Tensor`, *optional*):
              Negative T5 prompt attention mask generated by the text encoder step.
          num_images_per_prompt (`int`, *optional*, defaults to 1):
              The number of images to generate per prompt.
          height (`int`, *optional*):
              The height in pixels of the generated image.
          width (`int`, *optional*):
              The width in pixels of the generated image.
          latents (`Tensor`, *optional*):
              Pre-generated noisy latents for image generation.
          generator (`Generator`, *optional*):
              Torch generator for deterministic generation.
          num_inference_steps (`int`, *optional*, defaults to 50):
              The number of denoising steps.
          sigmas (`list`, *optional*):
              Custom sigmas for the denoising process.
          **denoiser_input_fields (`None`, *optional*):
              The conditional model inputs for the Anima denoiser.

      Outputs:
          latents (`Tensor`):
              Denoised latents.
    """

    block_classes = [
        AnimaTextConditioningStep,
        AnimaTextInputStep,
        AnimaPrepareLatentsStep,
        AnimaSetTimestepsStep,
        AnimaDenoiseStep,
    ]
    block_names = ["text_conditioning", "input", "prepare_latents", "set_timesteps", "denoise"]

    @property
    def description(self) -> str:
        return "Denoise block that takes encoded Anima text inputs and runs the denoising process."

    @property
    def outputs(self):
        return [OutputParam.template("latents")]


# auto_docstring
class AnimaDecodeStep(SequentialPipelineBlocks):
    """
    Decode Anima latents into generated images.

      Components:
          vae (`AutoencoderKLQwenImage`) image_processor (`VaeImageProcessor`)

      Inputs:
          latents (`Tensor`):
              Denoised Anima latents.
          output_type (`str`, *optional*, defaults to pil):
              Output format: 'pil', 'np', 'pt'.

      Outputs:
          images (`list`):
              Generated images.
    """

    block_classes = [AnimaVaeDecoderStep, AnimaProcessImagesOutputStep]
    block_names = ["decode", "postprocess"]

    @property
    def description(self) -> str:
        return "Decode Anima latents into generated images."

    @property
    def outputs(self):
        return [OutputParam.template("images")]


# auto_docstring
class AnimaAutoBlocks(SequentialPipelineBlocks):
    """
    Auto Modular pipeline for text-to-image generation using Anima.

      Supported workflows:
        - `text2image`: requires `prompt`

      Components:
          text_encoder (`Qwen3Model`) tokenizer (`Qwen2Tokenizer`) t5_tokenizer (`T5Tokenizer`) guider
          (`ClassifierFreeGuidance`) text_conditioner (`AnimaTextConditioner`) transformer (`CosmosTransformer3DModel`)
          scheduler (`FlowMatchEulerDiscreteScheduler`) vae (`AutoencoderKLQwenImage`) image_processor
          (`VaeImageProcessor`)

      Inputs:
          prompt (`str`):
              The prompt or prompts to guide image generation.
          negative_prompt (`str`, *optional*):
              The prompt or prompts not to guide the image generation.
          max_sequence_length (`int`, *optional*, defaults to 512):
              Maximum sequence length for prompt encoding.
          num_images_per_prompt (`int`, *optional*, defaults to 1):
              The number of images to generate per prompt.
          height (`int`, *optional*):
              The height in pixels of the generated image.
          width (`int`, *optional*):
              The width in pixels of the generated image.
          latents (`Tensor`, *optional*):
              Pre-generated noisy latents for image generation.
          generator (`Generator`, *optional*):
              Torch generator for deterministic generation.
          num_inference_steps (`int`, *optional*, defaults to 50):
              The number of denoising steps.
          sigmas (`list`, *optional*):
              Custom sigmas for the denoising process.
          **denoiser_input_fields (`None`, *optional*):
              The conditional model inputs for the Anima denoiser.
          output_type (`str`, *optional*, defaults to pil):
              Output format: 'pil', 'np', 'pt'.

      Outputs:
          images (`list`):
              Generated images.
    """

    block_classes = [
        AnimaTextEncoderStep,
        AnimaCoreDenoiseStep,
        AnimaDecodeStep,
    ]
    block_names = ["text_encoder", "denoise", "decode"]
    _workflow_map = {"text2image": {"prompt": True}}

    @property
    def description(self) -> str:
        return "Auto Modular pipeline for text-to-image generation using Anima."

    @property
    def outputs(self):
        return [OutputParam.template("images")]


# auto_docstring
class AnimaImg2ImgCoreDenoiseStep(SequentialPipelineBlocks):
    """
    Denoise block for Anima image-to-image generation. VAE encoding runs after AnimaTextInputStep so batch_size is
    available in state.

      Components:
          text_conditioner (`AnimaTextConditioner`) transformer (`CosmosTransformer3DModel`) vae
          (`AutoencoderKLQwenImage`) scheduler (`FlowMatchEulerDiscreteScheduler`) image_processor
          (`VaeImageProcessor`) guider (`ClassifierFreeGuidance`)

      Inputs:
          qwen_prompt_embeds (`Tensor`):
              Qwen prompt embeddings generated by the text encoder step.
          qwen_attention_mask (`Tensor`):
              Qwen prompt attention mask generated by the text encoder step.
          t5_input_ids (`Tensor`):
              T5 prompt token ids generated by the text encoder step.
          t5_attention_mask (`Tensor`):
              T5 prompt attention mask generated by the text encoder step.
          negative_qwen_prompt_embeds (`Tensor`, *optional*):
              Negative Qwen prompt embeddings generated by the text encoder step.
          negative_qwen_attention_mask (`Tensor`, *optional*):
              Negative Qwen prompt attention mask generated by the text encoder step.
          negative_t5_input_ids (`Tensor`, *optional*):
              Negative T5 prompt token ids generated by the text encoder step.
          negative_t5_attention_mask (`Tensor`, *optional*):
              Negative T5 prompt attention mask generated by the text encoder step.
          num_images_per_prompt (`int`, *optional*, defaults to 1):
              The number of images to generate per prompt.
          image (`Image | list`):
              Reference image(s) for denoising. Can be a single image or list of images.
          height (`int`, *optional*):
              The height in pixels of the generated image.
          width (`int`, *optional*):
              The width in pixels of the generated image.
          strength (`float`, *optional*, defaults to 0.9):
              Strength for img2img/inpainting.
          generator (`Generator`, *optional*):
              Torch generator for deterministic generation.
          latents (`Tensor`, *optional*):
              Pre-generated noisy latents for image generation.
          timesteps (`Tensor`):
              Timesteps for the denoising process.
          num_inference_steps (`int`):
              Total number of inference steps from AnimaImg2ImgSetTimestepsStep.
          **denoiser_input_fields (`None`, *optional*):
              The conditional model inputs for the Anima denoiser.

      Outputs:
          latents (`Tensor`):
              Denoised latents.
    """

    block_classes = [
        AnimaTextConditioningStep,
        AnimaTextInputStep,
        AnimaImg2ImgVaeEncoderStep,
        AnimaDenoiseStep,
    ]
    block_names = ["text_conditioning", "input", "vae_encoder", "denoise"]

    @property
    def description(self) -> str:
        return (
            "Denoise block for Anima image-to-image generation. "
            "VAE encoding runs after AnimaTextInputStep so batch_size is available in state."
        )

    @property
    def outputs(self):
        return [OutputParam.template("latents")]


# auto_docstring
class AnimaImg2ImgAutoBlocks(SequentialPipelineBlocks):
    """
    Auto Modular pipeline for image-to-image generation using Anima.

      Supported workflows:
        - `img2img`: requires `prompt`, `image`

      Components:
          text_encoder (`Qwen3Model`) tokenizer (`Qwen2Tokenizer`) t5_tokenizer (`T5Tokenizer`) guider
          (`ClassifierFreeGuidance`) scheduler (`FlowMatchEulerDiscreteScheduler`) text_conditioner
          (`AnimaTextConditioner`) transformer (`CosmosTransformer3DModel`) vae (`AutoencoderKLQwenImage`)
          image_processor (`VaeImageProcessor`)

      Inputs:
          prompt (`str`):
              The prompt or prompts to guide image generation.
          negative_prompt (`str`, *optional*):
              The prompt or prompts not to guide the image generation.
          max_sequence_length (`int`, *optional*, defaults to 512):
              Maximum sequence length for prompt encoding.
          num_inference_steps (`int`, *optional*, defaults to 50):
              The number of denoising steps.
          sigmas (`list`, *optional*):
              Custom sigmas for the denoising process.
          num_images_per_prompt (`int`, *optional*, defaults to 1):
              The number of images to generate per prompt.
          image (`Image | list`):
              Reference image(s) for denoising. Can be a single image or list of images.
          height (`int`, *optional*):
              The height in pixels of the generated image.
          width (`int`, *optional*):
              The width in pixels of the generated image.
          strength (`float`, *optional*, defaults to 0.9):
              Strength for img2img/inpainting.
          generator (`Generator`, *optional*):
              Torch generator for deterministic generation.
          latents (`Tensor`, *optional*):
              Pre-generated noisy latents for image generation.
          **denoiser_input_fields (`None`, *optional*):
              The conditional model inputs for the Anima denoiser.
          output_type (`str`, *optional*, defaults to pil):
              Output format: 'pil', 'np', 'pt'.

      Outputs:
          images (`list`):
              Generated images.
    """

    block_classes = [
        AnimaTextEncoderStep,
        AnimaImg2ImgSetTimestepsStep,
        AnimaImg2ImgCoreDenoiseStep,
        AnimaDecodeStep,
    ]
    block_names = ["text_encoder", "set_timesteps", "denoise", "decode"]
    _workflow_map = {"img2img": {"prompt": True, "image": True}}

    @property
    def description(self) -> str:
        return "Auto Modular pipeline for image-to-image generation using Anima."

    @property
    def outputs(self):
        return [OutputParam.template("images")]
