dir ="/home/arif/Documents/design/sandpit/sdv2/stablediffusion/outputs/txt2img-samples/samples"
owldir='/home/arif/Documents/design/sandpit/classimages/owl'
beardir='/home/arif/Documents/design/sandpit/classimages/bear'
donkeydir='/home/arif/Documents/design/sandpit/classimages/donkey'
forestdir='/home/arif/Documents/design/sandpit/classimages/forest'
pigletdir='/home/arif/Documents/design/sandpit/classimages/piglet'
rabbitdir='/home/arif/Documents/design/sandpit/classimages/rabbit'
Kangaroodir='/home/arif/Documents/design/sandpit/classimages/Kangaroo'
boydir = '/home/arif/Documents/design/sandpit/classimages/boy'
girldir='/home/arif/Documents/design/sandpit/classimages/girl'
womandir='/home/arif/Documents/design/sandpit/classimages/imageswoman'
promptsdir='/home/arif/Documents/design/sandpit/prompts'
all_imges='/home/arif/Documents/design/sandpit/classimages/allimages'



gwaladir='/home/arif/Documents/design/sandpit/instanceImages/gwala'
wunzagdir='/home/arif/Documents/design/sandpit/instanceImages/wunzag'
eyorddir='/home/arif/Documents/design/sandpit/instanceImages/eyord'
hadacoddir='/home/arif/Documents/design/sandpit/instanceImages/hadacod'
rigleldir='/home/arif/Documents/design/sandpit/instanceImages/riglel'
rawdibdir='/home/arif/Documents/design/sandpit/instanceImages/rawdib'
ungeradir='/home/arif/Documents/design/sandpit/instanceImages/ungera'
extoferdir = '/home/arif/Documents/design/sandpit/instanceImages/extofer'
renwadir='/home/arif/Documents/design/sandpit/instanceImages/renwa'
winzrigdir='/home/arif/Documents/design/sandpit/instanceImages/winzrig'