model_id: Wan-AI/Wan2.2-T2V-A14B-Diffusers
weight_path: /home/weights/Wan2.2-T2V-A14B-Diffusers
backend: modelscope
extra_params:
  boundary_ratio: 0.875
  guidance_scale_2: 5.0
  expand_timesteps: false
