name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release
      - v*-patch
    paths:
      - "src/diffusers/**.py"
      - "examples/**"
      - "docs/**"

permissions:
  contents: read

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@af49b8dc3859c3d80c7220c8c0ba146431132e49  # main
    with:
      commit_sha: ${{ github.sha }}
      install_libgl1: true
      package: diffusers
      notebook_folder: diffusers_doc
      languages: en ko zh ja pt
      pre_command: uv pip uninstall transformers huggingface_hub && UV_PRERELEASE=allow uv pip install -U transformers@git+https://github.com/huggingface/transformers.git
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
