name: Check Documentation Links

on:
  pull_request:
    paths:
      - "src/diffusers/**.py"
      - "examples/**"
      - "docs/**"
  push:
    branches:
      - main
      - doc-builder*
      - v*-release
      - v*-patch
    paths:
      - "src/diffusers/**.py"
      - "examples/**"
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install doc-builder
        run: |
          uv pip install --system git+https://github.com/huggingface/doc-builder.git@main

      - name: Check documentation links
        run: |
          uv run doc-builder check-links docs/source
