name: PR Style Bot

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read

jobs:
  style:
    uses: huggingface/huggingface_hub/.github/workflows/style-bot-action.yml@42642d4a896bd43a8360b29f5f32934232f4db32
    with:
      python_quality_dependencies: "[quality]"
    secrets:
      app_id: ${{ secrets.HF_BOT_STYLE_APP_ID }}
      app_private_key: ${{ secrets.HF_BOT_STYLE_SECRET_PEM }}
