name: PR Style Bot

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read

jobs:
  style:
    uses: huggingface/huggingface_hub/.github/workflows/style-bot-action.yml@e2867e92c07d15e1bf18994d0a945ef5ad6b8d65
    with:
      python_quality_dependencies: "[quality]"
    secrets:
      app_id: ${{ secrets.HF_BOT_STYLE_APP_ID }}
      app_private_key: ${{ secrets.HF_BOT_STYLE_SECRET_PEM }}
