name: Run Torch dependency tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/diffusers/**.py"
      - "tests/**.py"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check_torch_dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install torch pytest
      - name: Check for soft dependencies
        run: |
            pytest tests/others/test_dependencies.py
