on:
  push:

name: Secret Leaks


permissions: {}

jobs:
  trufflehog:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@f714bf454f350590f4a24c3ddb1aef02c35bf5b6 # v3.97.5
      with:
        extra_args: --results=verified,unknown

