on:
  push:

name: Secret Leaks


permissions: {}

jobs:
  trufflehog:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@4dd8831c5f12599465d4d45c3c447b4018a34c85  # main
      with:
        extra_args: --results=verified,unknown

