name: Check typos

on:
  workflow_dispatch:


permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: typos-action
        uses: crate-ci/typos@512fc24f32f44ab01972217aaaf3dc86ec234d53  # v1.50.2
